name: test

on: [push]

env:
  FORCE_COLOR: 3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run prettier
      - run: npm run build
      - run: npm test
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snapshots
          path: src/test/snapshots
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
